-- video_qa_migration.sql
-- Creates tables for the Video QA + Remediation Layer:
--   actp_post_metrics   — per-post performance metrics (views, saves, reach, etc.)
--   video_qa_learnings  — QA inspection results + retry/trash decisions with learnings
--
-- Apply via Supabase MCP: apply_migration(name="video_qa_tables", query=<this file>)
-- Or paste directly into Supabase SQL editor.

-- ─── actp_post_metrics ────────────────────────────────────────────────────────
-- Stores metrics polled from YouTube/Twitter/Instagram/TikTok/LinkedIn APIs.
-- The metrics poller upserts here on each check cycle.

CREATE TABLE IF NOT EXISTS actp_post_metrics (
  id                UUID DEFAULT gen_random_uuid() PRIMARY KEY,

  -- Reference to the original submission
  submission_id     UUID REFERENCES actp_blotato_submissions(id) ON DELETE CASCADE,
  platform          TEXT NOT NULL,      -- instagram | tiktok | youtube | twitter | linkedin
  post_url          TEXT,               -- URL of the live post
  blotato_post_id   TEXT,              -- Blotato's internal post ID (if available)

  -- Core metrics
  views             INTEGER DEFAULT 0,
  likes             INTEGER DEFAULT 0,
  comments          INTEGER DEFAULT 0,
  shares            INTEGER DEFAULT 0,
  saves             INTEGER DEFAULT 0,
  reach             INTEGER DEFAULT 0,
  impressions       INTEGER DEFAULT 0,
  profile_visits    INTEGER DEFAULT 0,

  -- Derived metrics
  engagement_rate   FLOAT GENERATED ALWAYS AS (
    CASE WHEN GREATEST(views, impressions, reach) > 0
    THEN CAST(likes + comments + shares + saves AS FLOAT) / GREATEST(views, impressions, reach) * 100
    ELSE 0 END
  ) STORED,

  -- Source tracking
  metric_source     TEXT NOT NULL DEFAULT 'blotato',  -- blotato | youtube_api | twitter_api | linkedin_api
  checked_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  -- Age-based tier (updated by poller)
  post_age_hours    INTEGER,
  performance_tier  TEXT,  -- top | strong | average | weak (Thompson Sampling input)

  created_at        TIMESTAMPTZ DEFAULT NOW(),
  updated_at        TIMESTAMPTZ DEFAULT NOW()
);

-- Unique constraint: one metric row per submission per check time
CREATE UNIQUE INDEX IF NOT EXISTS actp_post_metrics_submission_time_idx
  ON actp_post_metrics (submission_id, checked_at);

-- Index for time-range queries
CREATE INDEX IF NOT EXISTS actp_post_metrics_checked_at_idx
  ON actp_post_metrics (checked_at DESC);

-- Index for platform queries
CREATE INDEX IF NOT EXISTS actp_post_metrics_platform_idx
  ON actp_post_metrics (platform, checked_at DESC);

-- Auto-update updated_at
CREATE OR REPLACE FUNCTION update_actp_post_metrics_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_actp_post_metrics_updated ON actp_post_metrics;
CREATE TRIGGER trg_actp_post_metrics_updated
  BEFORE UPDATE ON actp_post_metrics
  FOR EACH ROW EXECUTE FUNCTION update_actp_post_metrics_updated_at();

-- ─── video_qa_learnings ───────────────────────────────────────────────────────
-- Stores QA inspection results for every video that:
--   (a) required ≥2 attempts, OR
--   (b) was trashed after hitting max retries
-- Used by Thompson Sampling to improve future parameter choices.

CREATE TABLE IF NOT EXISTS video_qa_learnings (
  id                UUID DEFAULT gen_random_uuid() PRIMARY KEY,

  -- Video identity
  clip_id           TEXT NOT NULL,   -- source clip identifier (media item ID or test ID)
  brand_id          TEXT NOT NULL,   -- isaiah_personal | everreach | portal_copy_co | techmestuff

  -- QA scores + decisions
  qa_score          INTEGER NOT NULL CHECK (qa_score >= 0 AND qa_score <= 100),
  caption_state     TEXT NOT NULL,   -- captions_present_good | captions_present_bad | captions_missing
  hook_state        TEXT NOT NULL,   -- hook_present_strong | hook_present_weak | hook_missing
  duration_delta_pct FLOAT NOT NULL, -- absolute % difference from source duration
  qa_decision       TEXT NOT NULL,   -- pass | improve | recreate | trash

  -- Retry tracking
  attempt_number    INTEGER NOT NULL DEFAULT 1,
  max_attempts      INTEGER NOT NULL DEFAULT 3,

  -- Issues found during QA
  qa_issues         JSONB DEFAULT '[]'::jsonb,  -- array of issue strings

  -- Generated content (when hook was generated by AI)
  suggested_hook    TEXT,
  hook_generated_at TIMESTAMPTZ,

  -- Learning categories (for filtering / analysis)
  learning_tags     JSONB DEFAULT '[]'::jsonb,  -- ["caption_missing", "duration_ok", etc.]

  created_at        TIMESTAMPTZ DEFAULT NOW()
);

-- Index for brand + decision queries
CREATE INDEX IF NOT EXISTS video_qa_learnings_brand_decision_idx
  ON video_qa_learnings (brand_id, qa_decision, created_at DESC);

-- Index for clip history (how many times was this clip attempted)
CREATE INDEX IF NOT EXISTS video_qa_learnings_clip_idx
  ON video_qa_learnings (clip_id, attempt_number);

-- ─── RLS (disabled — internal use only, no public access) ────────────────────
ALTER TABLE actp_post_metrics DISABLE ROW LEVEL SECURITY;
ALTER TABLE video_qa_learnings DISABLE ROW LEVEL SECURITY;

-- ─── Views ────────────────────────────────────────────────────────────────────

-- Latest metrics per submission (most recent check only)
CREATE OR REPLACE VIEW actp_post_metrics_latest AS
SELECT DISTINCT ON (submission_id)
  submission_id,
  platform,
  post_url,
  views,
  likes,
  comments,
  shares,
  saves,
  reach,
  engagement_rate,
  metric_source,
  checked_at,
  performance_tier
FROM actp_post_metrics
ORDER BY submission_id, checked_at DESC;

-- QA learning summary by brand
CREATE OR REPLACE VIEW video_qa_summary_by_brand AS
SELECT
  brand_id,
  qa_decision,
  COUNT(*) as count,
  ROUND(AVG(qa_score), 1) as avg_score,
  ROUND(AVG(duration_delta_pct), 2) as avg_duration_delta_pct,
  COUNT(*) FILTER (WHERE caption_state = 'captions_missing') as missing_captions,
  COUNT(*) FILTER (WHERE hook_state = 'hook_missing') as missing_hooks
FROM video_qa_learnings
GROUP BY brand_id, qa_decision
ORDER BY brand_id, qa_decision;
